import React, { useState } from 'react';
import { SafeAreaView } from 'react-native-safe-area-context';
import {
  Box,
  VStack,
  Text,
  Input,
  InputField,
  Button,
  ButtonText,
} from '@gluestack-ui/themed';
import { useColorMode } from '@/src/hooks/useColorMode';
import { useNavigation } from '@react-navigation/native';
import { Header } from '@/src/components/Header';
import { useToast, Toast, ToastTitle, ToastDescription } from '@gluestack-ui/themed';

export const GoogleAuthenticatorVerifyScreen = () => {
  const { colorMode } = useColorMode();
  const isDark = colorMode === 'dark';
  const navigation = useNavigation();
  const toast = useToast();

  const [code, setCode] = useState('');

  const handleComplete = async () => {
    if (!code || code.length !== 6) {
      toast.show({
        placement: 'top',
        render: ({ id }) => {
          return (
            <Box maxWidth="90%" alignSelf="center" px="$4">
              <Toast nativeID={`toast-${id}`} action="error" variant="solid">
                <ToastTitle>Geçersiz Kod</ToastTitle>
                <ToastDescription>Lütfen 6 haneli kodu girin.</ToastDescription>
              </Toast>
            </Box>
          );
        },
      });
      return;
    }

    // TODO: API call to verify code
    try {
      // const result = await verifyGoogleAuthenticatorCode(code);
      console.log('Verifying code:', code);
      
      toast.show({
        placement: 'top',
        render: ({ id }) => {
          return (
            <Box maxWidth="90%" alignSelf="center" px="$4">
              <Toast nativeID={`toast-${id}`} action="success" variant="solid">
                <ToastTitle>Başarılı</ToastTitle>
                <ToastDescription>Google Authenticator başarıyla etkinleştirildi.</ToastDescription>
              </Toast>
            </Box>
          );
        },
      });

      navigation.goBack();
      navigation.goBack(); // Go back to TwoFactorAuthScreen
    } catch (error: any) {
      toast.show({
        placement: 'top',
        render: ({ id }) => {
          return (
            <Box maxWidth="90%" alignSelf="center" px="$4">
              <Toast nativeID={`toast-${id}`} action="error" variant="solid">
                <ToastTitle>Hata</ToastTitle>
                <ToastDescription>
                  {error?.response?.data?.message || 'Kod doğrulanamadı. Lütfen tekrar deneyin.'}
                </ToastDescription>
              </Toast>
            </Box>
          );
        },
      });
    }
  };

  return (
    <SafeAreaView edges={['top', 'bottom', 'left', 'right']} style={{ flex: 1 }}>
      <Box
        flex={1}
        bg={isDark ? '$backgroundDark950' : '#FAFAFA'}
      >
        <Header
          title="Google Authenticator"
          showBackButton={true}
          onBackPress={() => navigation.goBack()}
        />

        <VStack flex={1} px="$4" py="$6" space="lg" justifyContent="center">
          <Text
            fontSize={22}
            fontWeight="$bold"
            color={isDark ? '#FFFFFF' : '#000000'}
            mb="$2"
          >
            Enter Code
          </Text>

          <Text
            fontSize={11}
            color={isDark ? '#FFFFFF' : '#000000'}
            mb="$6"
          >
            Enter the 6-digit code generated by Google Authenticator
          </Text>

          {/* Code Input */}
          <Box
            borderWidth={1}
            borderColor="#B9B9B9"
            borderRadius={10}
            px="$4"
            py="$1"
            mb="$6"
          >
            <Input borderWidth={0} bg="transparent">
              <InputField
                placeholder="Enter code"
                placeholderTextColor="#B9B9B9"
                value={code}
                onChangeText={(text) => {
                  // Sadece rakamları kabul et ve max 6 karakter
                  const numericValue = text.replace(/[^0-9]/g, '').slice(0, 6);
                  setCode(numericValue);
                }}
                keyboardType="number-pad"
                maxLength={6}
                color={isDark ? '#FFFFFF' : '#000000'}
                fontSize={14}
                textAlign="center"
              />
            </Input>
          </Box>
        </VStack>

        {/* Complete Button */}
        <Box px="$4" pb="$4" pt="$2">
          <Button
            bg="#E2FF46"
            borderRadius={8}
            onPress={handleComplete}
            disabled={code.length !== 6}
            opacity={code.length === 6 ? 1 : 0.5}
          >
            <ButtonText
              color="#000000"
              fontSize={14}
              fontWeight="$bold"
              textAlign="center"
            >
              Tamamla
            </ButtonText>
          </Button>
        </Box>
      </Box>
    </SafeAreaView>
  );
};

export default GoogleAuthenticatorVerifyScreen;

